// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://njzbfqqzvnuagweuowhs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5qemJmcXF6dm51YWd3ZXVvd2hzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4NTUxNzQsImV4cCI6MjA2OTQzMTE3NH0._eT4Gg9oxdBJWRik9rSAZIJJC59k5-lbDIDp225QP-M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});